/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CreatorSchema extends BaseModel {
  static $columns = ['createdAt', 'displayName', 'id', 'login', 'thumbnail', 'twitchId', 'updatedAt', 'userId'] as const
  $columns = CreatorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare login: string
  @column()
  declare thumbnail: string | null
  @column()
  declare twitchId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class JobSchema extends BaseModel {
  static $columns = ['clips', 'createdAt', 'creatorId', 'customTitle', 'error', 'hotPoints', 'id', 'progress', 'status', 'stepTimings', 'streamDate', 'streamer', 'streamerThumbnail', 'updatedAt', 'url', 'userId', 'viewCount', 'vodDurationSeconds', 'vodGame', 'vodGameId', 'vodGameThumbnail', 'vodTitle'] as const
  $columns = JobSchema.$columns
  @column()
  declare clips: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare creatorId: number | null
  @column()
  declare customTitle: string | null
  @column()
  declare error: string | null
  @column()
  declare hotPoints: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare progress: string | null
  @column()
  declare status: string
  @column()
  declare stepTimings: any | null
  @column()
  declare streamDate: string | null
  @column()
  declare streamer: string | null
  @column()
  declare streamerThumbnail: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: number | null
  @column()
  declare viewCount: number | null
  @column()
  declare vodDurationSeconds: number | null
  @column()
  declare vodGame: string | null
  @column()
  declare vodGameId: string | null
  @column()
  declare vodGameThumbnail: string | null
  @column()
  declare vodTitle: string | null
}

export class RenderSchema extends BaseModel {
  static $columns = ['batchGroupId', 'clipFilename', 'clipName', 'createdAt', 'error', 'id', 'jobId', 'outputFilename', 'progress', 'sizeMb', 'status', 'updatedAt', 'userId'] as const
  $columns = RenderSchema.$columns
  @column()
  declare batchGroupId: string | null
  @column()
  declare clipFilename: string
  @column()
  declare clipName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare jobId: string
  @column()
  declare outputFilename: string | null
  @column()
  declare progress: number
  @column()
  declare sizeMb: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class ThemeSchema extends BaseModel {
  static $columns = ['builtIn', 'createdAt', 'id', 'isDefault', 'layers', 'name', 'updatedAt', 'userId'] as const
  $columns = ThemeSchema.$columns
  @column()
  declare builtIn: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare layers: any
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class UserPermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permission', 'userId'] as const
  $columns = UserPermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permission: string
  @column()
  declare userId: number
}

export class UserQuotaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'limit', 'period', 'userId'] as const
  $columns = UserQuotaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare limit: number
  @column()
  declare period: string
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
