/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobSchema extends BaseModel {
  static $columns = ['clips', 'createdAt', 'error', 'hotPoints', 'id', 'progress', 'status', 'stepTimings', 'streamDate', 'streamer', 'streamerId', 'updatedAt', 'url', 'userId', 'viewCount', 'vodDurationSeconds', 'vodGame', 'vodTitle'] as const
  $columns = JobSchema.$columns
  @column()
  declare clips: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare error: string | null
  @column()
  declare hotPoints: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare progress: string | null
  @column()
  declare status: string
  @column()
  declare stepTimings: any | null
  @column()
  declare streamDate: string | null
  @column()
  declare streamer: string | null
  @column()
  declare streamerId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: number | null
  @column()
  declare viewCount: number | null
  @column()
  declare vodDurationSeconds: number | null
  @column()
  declare vodGame: string | null
  @column()
  declare vodTitle: string | null
}

export class RenderSchema extends BaseModel {
  static $columns = ['clipFilename', 'clipName', 'createdAt', 'error', 'id', 'jobId', 'outputFilename', 'progress', 'sizeMb', 'status', 'streamerId', 'updatedAt', 'userId'] as const
  $columns = RenderSchema.$columns
  @column()
  declare clipFilename: string
  @column()
  declare clipName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare jobId: string
  @column()
  declare outputFilename: string | null
  @column()
  declare progress: number
  @column()
  declare sizeMb: number | null
  @column()
  declare status: string
  @column()
  declare streamerId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class StreamerSchema extends BaseModel {
  static table = 'streamers'
  static $columns = ['avatarUrl', 'createdAt', 'displayName', 'id', 'twitchLogin', 'updatedAt'] as const
  $columns = StreamerSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare twitchLogin: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
