/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Assets: () => import('#controllers/assets_controller'),
  Clips: () => import('#controllers/clips_controller'),
  Jobs: () => import('#controllers/jobs_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Renders: () => import('#controllers/renders_controller'),
}
